sudo: false
language: java
jdk:
  - openjdk7
  - oraclejdk8
before_install:
   - "gem install faraday -v 0.8.9"
   - "gem install mime-types -v 2.6.2"
   - "gem install net-ssh -v 2.9.4"
   - "gem install travis-artifacts"
   - "export M2_HOME=/usr/local/maven"
   - "echo 'MAVEN_OPTS = $MAVEN_OPTS'"
install: "echo 'No install command here!'"
script: "mvn install -Pintegration-test -B"
after_failure: # this seems bust at the mo
  - "bash uploadSurefireReports.sh"
after_success:
  - "bash deploySnapshotBuild.sh"
env:
 global:
   - "MAVEN_OPTS=-Xmx3072m"
   - "ARTIFACTS_AWS_REGION=eu-west-1"
   - "ARTIFACTS_S3_BUCKET=eswdd.travis-ci"
   # S3 credentials
   - secure: "PMdX+2QqkQPpGbKiMRQDPRQeYNMLAqnXvnGb/EhEWdRF9o7pxten5AllxUAVXkx5b88X5x1wPhd4UZj43/lDoRLIwsnHe7Nstc3kWX4g0xXsKty2s2he40bu4Q7aZvsEfpTjm/KNe5cLVOcBKWP3ovgY4JFUP7qWz9R0Z+ttU5Y="
   - secure: "UIM47HAplfuaXAQLe3R10KpK1wCDtzVTLb2Vu6gp92JTlAxnMDJj7AYt0aN7ETaVF+6ZPac7kELQdufctcSKSD6N93tpOusw5yKmk2yk10t8uhzbXsHkN3scUi/0VSZ7gdHOWaNFVejtKSFOHqHOgN6ll93T0iviMhvl6xj7Y/c="
   # Sonatype Snapshot repo credentials
   - secure: "dN4cQEqoxAs4jMWLJqOfuJobSh7lqj5Ugo64sQcKLzJqpwBXaMyQvFsQxarWqbFWRjzSu8lw1+vQmz6R+dW6ysPDkQ/MqD1ETieBJjuQ46ynYMOVdR5hh4ovMnfCsCzpoaCdsuNFv+PwU6BN5LzQA7iKHSYDINzQKy1gobzzYtA="
   - secure: "bFEuZ3TbP/saFjqPF2naGi2QVRCfghMx/ztYR2GUuBy1NI70NSXkUhkob8Lyef2+zI9dDz4rF3+DocIb4Yx7BGoV16qxdOhGUPAKRyFKzgN9xH/8gSNJmtZvuHfrTA4lfluiu8NTbqBq7I2T4L4LQCldpmSvWgHr+Ag4hJ2kotk="
